services:
  prefect-worker:
    extends:
      file: docker-compose.yaml
      service: prefect-worker
    environment:
      - WHISPER_USE_CUDA=0
  devcontainer:
    extends:
      file: docker-compose.yaml
      service: devcontainer
    environment:
      - WHISPER_USE_CUDA=0
