services:
  # docker kill youtube-whisperer && docker rm youtube-whisperer
  # docker compose run --build --detach --name youtube-whisperer devcontainer
  # docker exec -it youtube-whisperer /bin/bash
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace/youtube-whisperer
      - ~/.whisper:/home/vscode/.whisper
      # Firefox cookies passthrough
      - ~/snap/firefox/common/.mozilla/firefox:/home/vscode/snap/firefox/common/.mozilla/firefox
    environment:
      - WHISPER_USE_CUDA=0
