services:
  devcontainer:
    extends:
      file: docker-compose.yaml
      service: devcontainer
    environment:
      - WHISPER_USE_CUDA=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  worker:
    extends:
      file: docker-compose.yaml
      service: worker
    environment:
      - WHISPER_USE_CUDA=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  redis:
    extends:
      file: docker-compose.yaml
      service: redis
