services:
  app:
    extends:
      file: docker-compose.cpu.yaml
      service: app
    environment:
      WHISPER_USE_CUDA: '1'
    runtime: nvidia

  whisper_worker:
    extends:
      file: docker-compose.cpu.yaml
      service: whisper_worker
    environment:
      WHISPER_USE_CUDA: '1'
    runtime: nvidia

  youtube_worker:
    extends:
      file: docker-compose.cpu.yaml
      service: youtube_worker

  azure_worker:
    extends:
      file: docker-compose.cpu.yaml
      service: azure_worker

  redis:
    extends:
      file: docker-compose.cpu.yaml
      service: redis

volumes:
  redis_vol:
