version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace/youtube_whisperer
      - ~/.whisper:/home/vscode/.whisper
    environment:
      - ASR_CUDA=0
