services:
  app:
    extends:
      file: docker-compose.yaml
      service: app
    environment:
      WHISPER_USE_CUDA: '1'
    runtime: nvidia

  worker:
    extends:
      file: docker-compose.yaml
      service: worker
    environment:
      WHISPER_USE_CUDA: '1'
    runtime: nvidia

  redis:
    extends:
      file: docker-compose.yaml
      service: redis

volumes:
  redis_vol:
