services:
  app:
    build:
      context: .
      args:
        APT_PROXY: http://192.168.0.4:3142
        PYPI_PROXY: http://192.168.0.4:3141/root/pypi/+simple/
    container_name: youtube-whisperer-app
    volumes:
      - .:/workspace/youtube-whisperer
      - ~/.whisper:/home/vscode/.whisper
      # FIXME: this only works on Linux
      - /media/libo/Videos/Transcode:/workspace/youtube-whisperer/assets
      - ~/snap/firefox/common/.mozilla/firefox:/home/vscode/snap/firefox/common/.mozilla/firefox
    environment:
      WHISPER_USE_CUDA: '0'
    depends_on:
      - redis
    ports:
      - "8000:8000"
    entrypoint: ["uvicorn", "youtube_whisperer.fastapi_app:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]

  worker:
    build:
      context: .
      args:
        APT_PROXY: http://192.168.0.4:3142
        PYPI_PROXY: http://192.168.0.4:3141/root/pypi/+simple/
    container_name: youtube-whisperer-worker
    volumes:
      - ~/.whisper:/home/vscode/.whisper
      - /media/libo/Videos/Transcode:/workspace/youtube-whisperer/assets
      - ~/snap/firefox/common/.mozilla/firefox:/home/vscode/snap/firefox/common/.mozilla/firefox
    environment:
      WHISPER_USE_CUDA: '0'
    depends_on:
      - redis
    entrypoint: ["python", "youtube_whisperer/worker.py"]

  redis:
    image: redis:latest
    container_name: youtube-whisperer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/data

volumes:
  redis_vol:
