[build-system]
requires = ["setuptools >= 64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "youtube-whisperer"
version = "0.0.1"
description = "Download video and run speech recognition"
requires-python = ">=3.10"
authors = [
  {name = "Libo Yin", email = "liboyin830@gmail.com"}
]
dependencies = [
  "azure-cognitiveservices-speech",
  "ctranslate2",
  "fastapi[standard]",
  "faster-whisper",
  "ffmpeg-python",
  "more-itertools",
  "pathlib-extensions@git+https://github.com/liboyin/pathlib-extensions.git",
  "redis",
  "soundfile",
  "youtube-transcript-api",
  "yt-dlp[default]",
]

[project.optional-dependencies]
dev = [
  "ipython",
  "mypy",
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "pytest-randomly",
  "ruff",
]

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=youtube_whisperer --cov-report=term-missing --cov-fail-under=80"

[tool.coverage.run]
branch = true

[tool.setuptools.packages.find]
include = ["youtube_whisperer*"]
